### ISSUE TITLE
很不错的插件，支持llama.cpp很赞，idea版本更新了，插件能不能也更新一下不然装不上了

### ISSUE THREAD

**Issue by riddlegit** [WisdomShell/codeshell-intellij#23]
如题

**Comment by Evermaple** [comment]
可以修改build.gradle.kts文件，patchPluginXml中的untilBuild.set("233.*")，把233改到你想支持的版本之后，然后重新build
版本号参考：https://www.jetbrains.com/idea/download/other.html

**Comment by riddlegit** [comment]
Thanks.
